### ISSUE TITLE
Generate constructors

### ISSUE THREAD

**Issue by demonkoryu** [goetas/xsd2php#76]
I can't comfortably use the xsd2php-generated classes for creating deep object trees, since there are no type-hinted constructors for complex types, like wsdl2phpgenerator has.

To show what I mean:

The current way requires to write everything backwards:

``` php
$rq = new SearchRequest();
$rq->setLanguageCode( 'de-DE' );
$rq->setTimestamp( new DateTime() );
$rq->setTarget( 'Fake' );
$search = new RegionListSearchType();
$trip = new TripType();
$journey = new JourneyType();
$traveller = new TravellerType();
$traveller->setAge(25);
$journey->setTravellerList([$traveller, $traveller]);
$journey->setDepartureAirportCountry('de');
$trip->setJourney($journey);
$search->setTrip($trip);
$options = new RegionListOptionsType();
$options->setResultsPerPage(1000);
$options->setResultOffset(0);
$search->setOptions($options);
$rq->setSearch($search);
```

The way I would like to use:

``` php
$rq = new Request( 
    'de-DE',
    new DateTime(),
    'Fake', 
    new Search( 
        new Trip( 
            new Journey( 
                [ new TravellerType( 25 ), new TravellerType( 25 ) ], 
                'de' 
            ) 
        ),
        new SearchOptions(0, 1000)
    )   
);
```

The constructor would have the nillable elements as default parameters with value `null`, just like wsdl2phpgenerator does.

**Comment by Ozmodiar** [comment]
@goetas What is your opinion on this? I'm currently working on this in https://github.com/Ozmodiar/xsd2php/tree/76-constructors

At this moment, I have made it so that all classes have a constructor with (mandatory) arguments for all properties except for classes that have a constructor set through a valuemethod.

A few ideas:
- This should probably be configurable and default off so the basic way of how the library works is not changed
- I think more config options are needed than just on/off, something like
  - --constructors='none' -> this or omitting the option does not generate constructors
  - --constructors='mandatory' -> add all properties to constructor arguments and make them mandatory
  - --constructors='optional' -> add all properties to constructor arguments and make them optional (default null)
  - --constructors='scaffold' -> this will create a constructor that will instantiate a new class of every subclass the class has. An example:

```php
class Accommodation
{
 /**
  * @property string $name
  */
  private $name = null;

 /**
  * @property Address $address
  */
  private $address = null;

 /**
  * Construct
  */
  public function __construct()
  {
    $this->address = new Address();
  }
}
```

The scaffold option can be useful for people that want to use the Symfony Property Access Component. This way they can simply create an instance of the Accommodation class and start hydrating the object (and the child objects) without having to create an instance of every child class himself. This makes for example the following possible:

```php
use Symfony\Component\PropertyAccess\PropertyAccess;

$accommodation = new Accommodation();

$accessor = PropertyAccess::createPropertyAccessor();
$accessor->setValue($accommodation, 'address.street', 'Downing Street');
$accessor->setValue($accommodation, 'address.number', 10);

// Or even deeper nesting
$accessor->setValue($accommodation, 'foo.bar.baz', 1);
```

What are your thoughts on this?

**Comment by goetas** [comment]
I was thinking months ago about this feature (can not find the issue on github) but I was not convinced on how to implement it... Your work looks good, and can be a nice feature to have.

> --constructors='mandatory' -> add all properties to constructor arguments and make them mandatory

What about optional tags/attributes, will they be mandatory too?

> --constructors='optional' -> add all properties to constructor arguments and make them optional (default null)

make sense

> --constructors='scaffold' -> this will create a constructor that will instantiate a new class of every subclass the class has.

This is the most controverse feature since you loose the control over your object. Plus, would be useful if this option can be combined with the `--constructors='optional'` option. 
```php
  public function __construct(Address $address=null)
  {
    $this->address = $address ?: new Address();
  }
```

Extra question: How do you decide the arguments order?

**Comment by goetas** [comment]
Consider that for some classes you will have 30/40 constructor arguments... does it make sense?

**Comment by goetas** [comment]
Is JMS serializer able to instantiate classes with mandatory argument? (I know doctrine is able using a `unserialize()` trick)

**Comment by Ozmodiar** [comment]
I agree that the constructor argument discussion can be a long one, so I would like to focus on the "scaffold" option without constructor arguments since it is something I really need and I don't see much harm in it.

I'm not really sure what you mean by "losing control over the object"? It remains possible at all times to use the setters to override the default created empty objects, no?

**Comment by goetas** [comment]
Custom plugins can solve this issue https://github.com/goetas/xsd2php/issues/100#issuecomment-172182214

**Comment by Ocramius** [comment]
Note: went ahead and implemented some of this stuff in a rush while trying to figure out how to generate better DTOs: https://gist.github.com/Ocramius/a7f99de6215a1cfa19b2fbd8873d1af9
